### ISSUE TITLE
Add builder-hex0-x86-stage1.bin bootstrap seed

### ISSUE THREAD

**Issue by rick-masters** [oriansj/bootstrap-seeds#38]
It has been suggested that the bootstrap seed for kernel bootstrapping in live-bootstrap be added to this project.

The file is builder-hex0-x86-stage1.bin which can be found in this PR: https://github.com/fosslinux/live-bootstrap/pull/295

I am not sure if this is the right place but I don't have any problem with it if it make sense to you.

I would put the file in NATIVE/x86 directory along with the source file builder-hex0-x86-stage1.hex0. I am open to using a different directory. I can also rename the binary to use the img extension if that is preferred.

The thing is: the bootstrap seed file is primarily a boot loader for builder-hex0-x86-stage2.hex0. It compiles stage2 into address 0x7E00 and then jumps to it. So, the seed is not useful by itself for creating a compiler (hex0) or shell (kaem). I could include the builder-hex0-x86-stage2.hex0 here source as well. Stage2 can compile any hex0 file and write it back to disk so in combination with the boot loader it forms a useful bootstrap. But I'm not sure if it makes sense to include a 75K kernel source file in this bootstrap-seed repository. Please let me know your thoughts on this.

Note that I won't be able to use this in live-bootstrap until stage0-posix pulls in a new bootstrap-seeds so that would need to be done as well.

I can provide a PR based on your advice or if you want to make the change feel free.

**Comment by stikonas** [comment]
As discussed before I think let's put `builder-hex0-x86-stage1.bin` and `builder-hex0-x86-stage1.hex0` here as well as some README with a short explanation that this is only useful to boot `builder-hex0-x86-stage2.hex0`.
