### ISSUE TITLE
Environment variable substitution

### ISSUE THREAD

**Issue by MagicRB** [oriansj/bootstrap-seeds#6]
I'm working with [SoN](https://summer.nixos.org/) and one of the projects in this program is GNU Mes and as far as I understand it, this is part of that. I want to use kaem to not depend on any already built programs, but in Nix it's common to specify the output path with `$out` in shell scripts, I can't find any way around it, since the output path is not known when the shell script is created. Could basic environment variable substitution be added? perhaps only working for `$out`?

**Comment by MagicRB** [comment]
Actually I figured out a way around this, but it would still be a nice "feature" :D

**Comment by oriansj** [comment]
actually this is not part of Gnu MES but one of a potentially infinite number of bootstrap roots. the actual dependency for Gnu MES is mescc-tools https://savannah.nongnu.org/projects/mescc-tools which can be built by any C compiler available or if you wish to bootstrap from a lower level can be build by M2-Planet https://github.com/oriansj/M2-Planet which can be bootstrapped from these seeds via: https://github.com/oriansj/stage0-posix which does bootstrap everything needed to bootstrap Gnu MES and everything else needed to bootstrap Linux+GCC: https://github.com/fosslinux/live-bootstrap 

That being said the primary goal of these binaries is to be as small as possible and include as little functionality as we can get away with. To which end adding this as a nice "feature" does not contribute to those goals. That being said the kaem-optional-seed should pass any environmental variables to the kaem.hex0 it builds in stage0-posix which could certainly grow that feature. Feel free to submit that request to stage0-posix but it isn't a feature that belongs in bootstrap-seeds.

**Comment by MagicRB** [comment]
Ok, sorry for the confusion. stage0 seemed to me like the unofficial official way to bootstrap GNU Mes, so I just kind of assumed its somehow officially related. Anyway, I'll open an issue in stage0-posix, I put it here since I was hoping I could get to `$out` as soon as possible preferably from bootstrap, it makes the resulting code a whole lot nicer. BTW, great project, it's fascinating how you got from a crappy hex assembler to a full C compiler.
